### PR TITLE
Added a few ideas...

### PR DESCRIPTION
**Pull request by rohjay**
Hey Mikey! Saw this on twitter and thought I'd contribute instead of twiddling my thumbs. Open to any feedback =]

Cheers!
Ryan

### CODE REVIEW

**Comment by rohjay** [comment]
Hey @WierdJulie ! While I *could* do it for you, I'm more of a "Teach a gal to fish" kinda guy - hope you don't mind.

## Step 1: Fork the Repo (looks like ya did it already!)
image
Bonk the fork button in the top right corner. It'll say something to the effect of "hey just a sec! Forkin' a repo for ya!". Once it's finished, it'll load your fork of the repo.

## Step 2: Clone or Download locally
image
Bonk the green "Clone or download" button. Here you have some choices (demonstrated by my awesome illustrations). If you're familiar with the command line, I would say a simple `git clone git@github.com:WierdJulie/wtfsidiq.git` should be easy enough! If not, the easiest way might be to use the [Github Desktop](https://desktop.github.com/) tool to clone it.

**QUICK NOTE**: Ensure that you clone from YOUR FORK, otherwise, the following commands might not work right due to the repo's default "remote" location. We can get into the basics of git specifically if you'd like =]

## Step 3: Open the file and make your changes
image
In this case, we want to open the `wtfsidiq.js` file inside the repo to make our desired changes. Don't forget the comma at the end of each new line in your code!!! (*watch, I totally forgot one... smh*)

## Step 4: Save, Commit & Push Changes
image
I saved my changes in my editor, then I ran a `git status` - to check the status of my changes. You can also run a `git diff` to see specifically what those changes were. I see the file I modified was in the list there (emphasized by my awesome arrow! KAPLOW!), and I'm confident about what I'm committing.

I then ran a `git commit -am "I've made changes - woohoo"` command. The `-am` means two things:
1. `a` - commit all files that aren't currently "staged". And...
2. `m` - I would like to specify the message for this commit... That message is "I've made changes - woohoo". If you're noobish on the command line, here's a protip: avoid punctuation like `!`'s - they'll bork up your command!

After I committed my changes, I "pushed" them to Github using the `git push origin new-pr-example` command. This is going to be a little different for you most likely. To demonstrate this, I made a new branch. Since you're on a fork, you didn't need to do that, so you're probably still on the `master branch`. You'll see in the image when I ran a `git status`, the first thing it told me was "On branch new-pr-example" - yours should probably say "On branch master". SO! You'll need to modify your command to `git push origin master` =]

If you use Github Desktop, it's a gui I'm not familiar with, but the lingo is probably going to be the same. Status -> Commit (with message) -> Push. Easy as pie!

## Create your Pull Request Against the Original Repository
Github makes this super easy actually. If you go back to the original repository (and/or many other pages related to this codebase), you'll see a little helper alert to create your Pull Request like this:
image

Woohoo! Bonk that button and fill out your pull request!

image

Once you're happy with the description (which normally has more pertinent info about the changes than this example's does), bonk the create pull request and you're done!

Hope this helps! Feel free to ask me any questions you have =]

Cheers,
Ryan

PS - sorry if this was over the top. You said you were a new Githubber, so I figured I'd be as descriptive as reasonably possible. Of course, absolutely feel free to ask questions though! =]

**Comment by WierdJulie** [comment]
Ryan, I tried but I’m done. I just can’t do it :( 
Sorry.

**Comment by rohjay** [comment]
No worries, @WierdJulie! Just like in the Matrix, nobody makes the first jump. But you tried! That's a baller first step - don't get discouraged =]

I'd be happy to walk you through it if you'd like. Reach out to me [on Kneejerk.dev](https://kneejerk.dev/#contact) and I'd be happy to help you out. SCM (source control management) isn't the easiest thing to grok at first!

Cheers,
Ryan

PS - honestly, you shoulda seen me day #1 at my first dev gig where I pretended to know what I was doing. Oi vey! I lost a lot of code the first couple weeks because I didn't ask questions xD

**Comment by rohjay** [comment]
@heyitsmikeyv - there's been a little side conversation in here. If you'd like, I can close this and re-open it. Let me know what you'd like man!

Cheers,
Ryan

**Comment by rohjay** [comment]
I'm going to go ahead and close this. No need to keep it open with as little activity here as there's been.

Thanks anyways, @heyitsmikeyv =]

**Pull request closed without merging**
